# Generated by Django 3.2.9 on 2022-01-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220102_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurnt',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
