# Generated by Django 3.2.9 on 2022-01-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
        ('restaurant', '0007_alter_addressuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressuser',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
    ]
